import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Card, ProgressBar } from '../components/design-system';

const XAI_DATABASE = {
  'liam-carter': {
    name: 'Liam Carter',
    age: '4 Years',
    riskScore: 76,
    overallConfidence: 94,
    biomarkers: [
      { name: 'Reduced Eye Contact', pct: 82, desc: 'Sustained social gaze under 12% baseline.' },
      { name: 'Speech Delay', pct: 74, desc: 'Vocal response latency averages 3.4 seconds.' },
      { name: 'Theta EEG Irregularity', pct: 61, desc: 'Fronto-central Theta/Beta ratio shift of 4.75.' }
    ],
    confidences: [
      { name: 'Visual CV Pipeline', val: 94 },
      { name: 'Acoustic Speech Pipeline', val: 88 },
      { name: 'Neural EEG Spectrum', val: 91 },
      { name: 'Questionnaire Domain', val: 95 }
    ],
    features: [
      { label: 'Computer Vision Gaze', val: 35, color: '#00ffcc' },
      { label: 'Neural EEG FFT Bands', val: 28, color: '#00d4ff' },
      { label: 'Audio Vocal Prosody', val: 22, color: '#a78bfa' },
      { label: 'Milestone Questionnaire', val: 15, color: '#f59e0b' }
    ],
    clinicalExplanation: "The risk score of 76/100 is generated by the Multimodal Fusion Engine due to the overlap of three major indicators. First, Computer Vision detected a joint attention gaze duration of only 12%, which is 5.4x below standard developmental controls. Second, the speech analysis model flagged a flat pitch affect. Third, the Frontal EEG spectrum recorded a Theta-to-Beta ratio of 4.75, which triggers the clinical attention threshold (> 2.5). The combination of these three anomalies across different sensor channels indicates high certainty of a Level 1 ASD developmental profile."
  },
  'lucas-davis': {
    name: 'Lucas Davis',
    age: '4 Years',
    riskScore: 82,
    overallConfidence: 96,
    biomarkers: [
      { name: 'Repetitive Motor Stereotypies', pct: 92, desc: 'Hand flapping and rocking index at 3.2Hz.' },
      { name: 'Gaze Smile Latency', pct: 85, desc: 'Delayed affect response averaging 4.1s.' },
      { name: 'EEG Fronto-Central TBR Shift', pct: 78, desc: 'Theta/Beta ratio verified at 5.12.' }
    ],
    confidences: [
      { name: 'Visual CV Pipeline', val: 96 },
      { name: 'Acoustic Speech Pipeline', val: 91 },
      { name: 'Neural EEG Spectrum', val: 95 },
      { name: 'Questionnaire Domain', val: 92 }
    ],
    features: [
      { label: 'Computer Vision Motor', val: 40, color: '#00ffcc' },
      { label: 'Neural EEG FFT Bands', val: 32, color: '#00d4ff' },
      { label: 'Audio Vocal Cadence', val: 18, color: '#a78bfa' },
      { label: 'Milestone Questionnaire', val: 10, color: '#f59e0b' }
    ],
    clinicalExplanation: "A risk score of 82/100 represents a high-severity trajectory. Computer Vision analysis tracked high-frequency motor stereotypies (3.2Hz rocking) that represent a heavy visual biomarker weighting (40%). Coupled with a highly elevated Frontal EEG ratio (5.12 TBR) and social communication delays, the system establishes a high-certainty alignment with Level 2 ASD criteria."
  },
  'noah-kline': {
    name: 'Noah Kline',
    age: '3 Years',
    riskScore: 68,
    overallConfidence: 90,
    biomarkers: [
      { name: 'Frontal TBR Wave Shift', pct: 85, desc: 'EEG spectral bands show 3.90 TBR ratio.' },
      { name: 'Joint Gaze Avoidance', pct: 70, desc: 'Attention focus duration is 18%.' },
      { name: 'Vocal Imitation Latency', pct: 64, desc: 'Acoustic response delay averaging 2.8s.' }
    ],
    confidences: [
      { name: 'Visual CV Pipeline', val: 88 },
      { name: 'Acoustic Speech Pipeline', val: 85 },
      { name: 'Neural EEG Spectrum', val: 90 },
      { name: 'Questionnaire Domain', val: 94 }
    ],
    features: [
      { label: 'Neural EEG FFT Bands', val: 36, color: '#00d4ff' },
      { label: 'Computer Vision Gaze', val: 28, color: '#00ffcc' },
      { label: 'Audio Vocal Prosody', val: 20, color: '#a78bfa' },
      { label: 'Milestone Questionnaire', val: 16, color: '#f59e0b' }
    ],
    clinicalExplanation: "Noah's risk score of 68/100 is predominantly guided by neural spectral features. The Frontal EEG ratio (3.90 TBR) is the leading model driver (36% attribution), supported by parent-reported social milestone delays and computer-vision flagged gaze gaps. Clinical neurological confirmation is recommended."
  },
  'oliver-thomas': {
    name: 'Oliver Thomas',
    age: '3 Years',
    riskScore: 74,
    overallConfidence: 91,
    biomarkers: [
      { name: 'Sensory Regulation Gaps', pct: 90, desc: 'Parent report indicates tactile avoidance.' },
      { name: 'Motor Gait Toe Walking', pct: 82, desc: 'Computer vision flagged toe walking sequences.' },
      { name: 'Gaze Smile Latency', pct: 74, desc: 'Delayed facial imitation at 3.1s.' }
    ],
    confidences: [
      { name: 'Visual CV Pipeline', val: 90 },
      { name: 'Acoustic Speech Pipeline', val: 84 },
      { name: 'Neural EEG Spectrum', val: 87 },
      { name: 'Questionnaire Domain', val: 95 }
    ],
    features: [
      { label: 'Milestone Questionnaire', val: 38, color: '#f59e0b' },
      { label: 'Computer Vision Motor', val: 32, color: '#00ffcc' },
      { label: 'Neural EEG FFT Bands', val: 18, color: '#00d4ff' },
      { label: 'Audio Vocal Prosody', val: 12, color: '#a78bfa' }
    ],
    clinicalExplanation: "Oliver's risk score of 74/100 is guided heavily by sensory hypo-reactivity items in parent surveys (38% weight) combined with computer-vision gait analysis showing toe walking and finger posturing (32% weight). The fusion engine suggests sensory integration needs matching OT support pathways."
  },
  'emma-larson': {
    name: 'Emma Larson',
    age: '6 Years',
    riskScore: 48,
    overallConfidence: 85,
    biomarkers: [
      { name: 'Vocal Echolalia Loops', pct: 85, desc: 'Repetitive phrases loops detected in speech.' },
      { name: 'Speech Response Gaps', pct: 78, desc: 'Cadence response latency averages 3.0s.' },
      { name: 'Gaze Focus Duration', pct: 32, desc: 'Mild gaze avoidance (35% focus).' }
    ],
    confidences: [
      { name: 'Visual CV Pipeline', val: 80 },
      { name: 'Acoustic Speech Pipeline', val: 92 },
      { name: 'Neural EEG Spectrum', val: 78 },
      { name: 'Questionnaire Domain', val: 88 }
    ],
    features: [
      { label: 'Audio Vocal Prosody', val: 48, color: '#a78bfa' },
      { label: 'Milestone Questionnaire', val: 24, color: '#f59e0b' },
      { label: 'Computer Vision Gaze', val: 18, color: '#00ffcc' },
      { label: 'Neural EEG FFT Bands', val: 10, color: '#00d4ff' }
    ],
    clinicalExplanation: "Emma's score of 48/100 represents a medium-risk borderline classification. The primary model weight rests in the acoustic pipeline (48% attribution), which recorded flat voice cadence and frequent phrase repetitions (echolalia). Cognitive and motor indicators fall within typical ranges."
  },
  'ava-wilson': {
    name: 'Ava Wilson',
    age: '5 Years',
    riskScore: 55,
    overallConfidence: 88,
    biomarkers: [
      { name: 'Sensory Regulation Score', pct: 82, desc: 'Tactile seek behaviors reported (42/100).' },
      { name: 'Motor Flapping Loops', pct: 76, desc: 'Occasional hand flapping (1.8Hz) tracked.' },
      { name: 'Frontal TBR Wave Shift', pct: 68, desc: 'EEG spectral ratio at 2.68 TBR.' }
    ],
    confidences: [
      { name: 'Visual CV Pipeline', val: 86 },
      { name: 'Acoustic Speech Pipeline', val: 82 },
      { name: 'Neural EEG Spectrum', val: 88 },
      { name: 'Questionnaire Domain', val: 91 }
    ],
    features: [
      { label: 'Milestone Questionnaire', val: 34, color: '#f59e0b' },
      { label: 'Computer Vision Motor', val: 28, color: '#00ffcc' },
      { label: 'Neural EEG FFT Bands', val: 22, color: '#00d4ff' },
      { label: 'Audio Vocal Prosody', val: 16, color: '#a78bfa' }
    ],
    clinicalExplanation: "Ava's risk score of 55/100 is moderately elevated, driven by parent-reported sensory processing challenges and computer-vision tracked hand flapping. Frontal spectrals show a minor TBR ratio shift (2.68), suggesting mild neurological indicators."
  },
  'sophia-miller': {
    name: 'Sophia Miller',
    age: '5 Years',
    riskScore: 28,
    overallConfidence: 92,
    biomarkers: [
      { name: 'Typical Joint Attention', pct: 15, desc: 'Standard gaze focus verified (58% focus).' },
      { name: 'Typical Speech Cadence', pct: 12, desc: 'Cadence delays within normal limits (1.2s).' },
      { name: 'Typical Frontal Ratio', pct: 8, desc: 'Typical spectral bands (1.85 TBR).' }
    ],
    confidences: [
      { name: 'Visual CV Pipeline', val: 94 },
      { name: 'Acoustic Speech Pipeline', val: 91 },
      { name: 'Neural EEG Spectrum', val: 93 },
      { name: 'Questionnaire Domain', val: 95 }
    ],
    features: [
      { label: 'Computer Vision Gaze', val: 32, color: '#00ffcc' },
      { label: 'Neural EEG FFT Bands', val: 28, color: '#00d4ff' },
      { label: 'Audio Vocal Prosody', val: 22, color: '#a78bfa' },
      { label: 'Milestone Questionnaire', val: 18, color: '#f59e0b' }
    ],
    clinicalExplanation: "Sophia's risk score of 28/100 falls well within the typical neurodevelopmental baseline. There are zero significant visual, vocal, or neural anomalies detected. All pipelines report high alignment with typical age milestones."
  }
};

export default function AIEvaluation() {
  const [searchParams, setSearchParams] = useSearchParams();
  const patientId = searchParams.get('patientId') || 'liam-carter';
  const currentPatient = XAI_DATABASE[patientId] || XAI_DATABASE['liam-carter'];

  return (
    <div className="space-y-6 pb-12">
      {/* Title */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
      >
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold text-[var(--app-text-primary)]">Explainable AI Insights</h1>
            <p className="text-[var(--app-text-muted)] mt-1">
              Interpret machine learning attributions, feature attributions (SHAP), and model metrics.
            </p>
          </div>
          {/* Patient Selector */}
          <div className="flex items-center gap-2 self-start md:self-auto bg-[var(--app-surface-muted)] border border-[var(--app-border)] p-1.5 rounded-lg">
            <span className="text-[10px] text-[var(--app-text-muted)] font-bold uppercase tracking-wider pl-2">Case file:</span>
            <select
              value={patientId}
              onChange={(e) => setSearchParams({ patientId: e.target.value })}
              className="bg-[var(--app-input-bg)] border border-[var(--app-border)] rounded-lg px-2.5 py-1.5 text-xs font-semibold text-[var(--accent-secondary)] focus:outline-none focus:border-[var(--accent-secondary)]/50 transition-all hover:bg-[var(--app-surface-muted)]"
            >
              {Object.keys(XAI_DATABASE).map((id) => (
                <option key={id} value={id}>
                  {XAI_DATABASE[id].name} ({XAI_DATABASE[id].age})
                </option>
              ))}
            </select>
          </div>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Left Column: Contributing Biomarkers & Confidence bars */}
        <div className="space-y-6">
          
          {/* Top Contributing Biomarkers */}
          <Card className="border border-[var(--app-border)] bg-[var(--app-surface)] space-y-4">
            <h3 className="text-xs font-bold text-[var(--accent-primary)] uppercase tracking-wider pb-2 border-b border-[var(--app-border)]">
              Top Contributing Biomarkers
            </h3>
            
            <div className="space-y-4">
              {currentPatient.biomarkers.map((bm, index) => (
                <div key={index} className="space-y-1">
                  <div className="flex justify-between text-xs font-semibold">
                    <span className="text-[var(--app-text-primary)]">{bm.name}</span>
                    <span className="text-[var(--accent-primary)] font-mono">{bm.pct}%</span>
                  </div>
                  <ProgressBar value={bm.pct} />
                  <p className="text-[10px] text-[var(--app-text-muted)]">{bm.desc}</p>
                </div>
              ))}
            </div>
          </Card>

          {/* Individual Pipeline Confidence Bars */}
          <Card className="border border-[var(--app-border)] bg-[var(--app-surface)] space-y-4">
            <h3 className="text-xs font-bold text-[var(--accent-secondary)] uppercase tracking-wider pb-2 border-b border-[var(--app-border)]">
              Multi-Channel Pipeline Certitude
            </h3>

            <div className="space-y-4">
              {currentPatient.confidences.map((pipe, index) => (
                <div key={index} className="space-y-1.5">
                  <div className="flex justify-between text-xs">
                    <span className="text-[var(--app-text-secondary)]">{pipe.name}</span>
                    <span className="text-[var(--app-text-primary)] font-mono font-bold">{pipe.val}%</span>
                  </div>
                  <div className="h-2 rounded-full bg-[var(--app-surface-muted)] overflow-hidden border border-[var(--app-border)]">
                    <motion.div
                      className="h-full rounded-full"
                      style={{
                        background: 'linear-gradient(90deg, var(--accent-secondary), var(--accent-primary))',
                      }}
                      initial={{ width: 0 }}
                      animate={{ width: `${pipe.val}%` }}
                      transition={{ delay: 0.1 * index, duration: 0.8 }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </Card>

        </div>

        {/* Right Column: Feature Importance & Clinical explanation */}
        <div className="space-y-6">
          
          {/* Feature Importance weights */}
          <Card className="border border-[var(--app-border)] bg-[var(--app-surface)] space-y-4">
            <h3 className="text-xs font-bold text-purple-400 uppercase tracking-wider pb-2 border-b border-[var(--app-border)]">
              SHAP Feature Attributions
            </h3>
            <p className="text-[10px] text-[var(--app-text-muted)]">Relative contribution weights of individual sensory channels in the fused classification.</p>

            <div className="space-y-4 pt-2">
              {currentPatient.features.map((feat, index) => (
                <div key={index} className="space-y-1">
                  <div className="flex justify-between text-xs font-semibold">
                    <span className="text-[var(--app-text-primary)]">{feat.label}</span>
                    <span className="font-mono" style={{ color: feat.color }}>{feat.val}%</span>
                  </div>
                  <div className="h-3 rounded-md bg-[var(--app-surface-muted)] border border-[var(--app-border)] overflow-hidden">
                    <motion.div
                      className="h-full rounded-md"
                      style={{
                        backgroundColor: feat.color,
                        boxShadow: `0 0 8px ${feat.color}40`,
                      }}
                      initial={{ width: 0 }}
                      animate={{ width: `${feat.val * 2.5}%` }} // normalized scaling
                      transition={{ delay: 0.1 * index, duration: 0.8 }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </Card>

          {/* Rationale explanation card */}
          <Card className="border border-[var(--app-border)] bg-[var(--app-surface)] space-y-4">
            <h3 className="text-xs font-bold text-[var(--app-text-primary)] uppercase tracking-wider pb-2 border-b border-[var(--app-border)] flex items-center gap-2">
              <span>🩺</span> Clinician Rationale Summary
            </h3>
            <div className="rounded-xl border border-[var(--app-border)] bg-[var(--app-surface-muted)] p-4 border-l-4 border-l-[var(--accent-primary)]">
              <h4 className="text-[10px] font-extrabold text-[var(--accent-primary)] uppercase tracking-wider mb-2">Why the AI Generated Risk Score ({currentPatient.riskScore}/100)</h4>
              <p className="text-xs text-[var(--app-text-secondary)] leading-relaxed font-[450] whitespace-pre-line">
                {currentPatient.clinicalExplanation}
              </p>
            </div>
            <p className="text-[9px] text-[var(--app-text-muted)] leading-normal">
              SHAP values calculated via kernel estimation. Model features are normalized across standard population age controls. For clinical triage guidance only.
            </p>
          </Card>

        </div>

      </div>

    </div>
  );
}
